apiVersion: v1
kind: Service
metadata:
  name: calc-deploy
  namespace: calc-deploy
  labels:
    app: calc-deploy
spec:
  selector:
    app: calc-deploy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
